title: James Bonaffini
email: james.bonaffini@gmail.com
description: Portfolio & Blog
github_username: jbonaffini
paginate: 5
remote_theme: fongandrew/hydeout
repo: https://github.com/jbonaffini
linkedin: https://www.linkedin.com/in/james-bonaffini/
hydeoutlink: https://github.com/fongandrew/hydeout
